#!/usr/bin/env bash

# Parallel version of the compile and test script

set -e

x=1000000

currentDirectory=$(pwd)

if [[ "$(uname -s)" == "Darwin" ]]; then
    currentDirectory="/Users/Jason/Documents/NewYorkUniversity/Junior-Year-Spring-2016/ParallelProgramming/Parallel-Computing-Lab-3-Finding-Max-Value"
fi

# Sets up CUDA if on CIMS
if [[ "$(uname -s)" == "Linux" ]]; then
	module load mpi/mpich-x86_64
	if [[ ! -d "$currentDirectory/samples" ]]; then
		cp -r /usr/local/cuda/samples $currentDirectory/samples
		cd $currentDirectory/samples
		make
		cd bin/x86_64/linux/release
		./deviceQuery
		./bandwidthTest
	fi
else
	if [[ ! -d "$currentDirectory/samples" ]]; then
		cp -r /Developer/NVIDIA/CUDA-7.5/samples $currentDirectory/samples
		cd $currentDirectory/samples
		make
		cd bin/x86_64/darwin/release
		./deviceQuery
		./bandwidthTest
	fi
fi
cd $currentDirectory

# Compiles
if [[ $(hostname | grep cuda1 ) ]]; then
nvcc -g -m64 \
--generate-code arch=compute_30,code=sm_30 \
--generate-code arch=compute_35,code=sm_35 \
--generate-code arch=compute_37,code=sm_37 \
--generate-code arch=compute_50,code=sm_50 \
--generate-code arch=compute_52,code=sm_52 \
--generate-code arch=compute_52,code=compute_52 \
-o maxgpu maxgpu.cu

else if [[ $(hostname | grep cuda5) ]]; then
nvcc -g -m64 \
--generate-code arch=compute_20,code=sm_20 \
--generate-code arch=compute_30,code=sm_30 \
--generate-code arch=compute_35,code=sm_35 \
--generate-code arch=compute_37,code=sm_37 \
--generate-code arch=compute_50,code=sm_50 \
--generate-code arch=compute_52,code=sm_52 \
--generate-code arch=compute_52,code=compute_52 \
-o maxgpu maxgpu.cu
fi

# Executes and generates the output file
./maxgpu $x
